export const jobTitles = [
    "Software Developer",
    "Software Engineer",
    "Full Stack Developer",
    "Front End Developer",
    "Back End Developer",
    "Web Developer",
    "Mobile App Developer",
    "UI/UX Designer",
    "Data Scientist",
    "Data Analyst",
    "Database Administrator",
    "DevOps Engineer",
    "Cloud Engineer",
    "Network Engineer",
    "System Administrator",
    "IT Support Specialist",
    "Technical Support Engineer",
    "Security Analyst",
    "Cybersecurity Specialist",
    "IT Manager",
    "Project Manager",
    "Product Manager",
    "Business Analyst",
    "QA Tester",
    "Quality Assurance Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Blockchain Developer",
    "IoT Engineer",
    "Software Architect",
    "Site Reliability Engineer",
    "Systems Analyst",
    "Technical Writer",
    "IT Consultant",
    "IT Director",
    "Chief Information Officer (CIO)",
    "Chief Technology Officer (CTO)",
    "Information Security Manager",
    "IT Auditor",
    "Network Administrator",
    "Help Desk Technician",
    "IT Coordinator",
    "Computer Programmer",
    "Game Developer",
    "Embedded Systems Engineer",
    "Hardware Engineer",
    "IT Trainer",
    "IT Specialist",
    "Cloud Solutions Architect",
    "Big Data Engineer",
    "Business Intelligence Developer",
    "Technical Account Manager",
    "IT Operations Manager",
    "Software Development Manager",
    "Application Support Analyst",
    "ERP Consultant",
    "Salesforce Developer",
    "SAP Consultant",
    "IT Project Coordinator",
    "Release Manager",
    "Data Engineer",
    "Business Systems Analyst",
    "Information Systems Manager",
    "E-Commerce Specialist",
    "Technical Program Manager",
    "User Experience Researcher",
    "Infrastructure Engineer",
    "IT Security Consultant",
    "Penetration Tester",
    "Digital Forensics Analyst",
    "System Integration Engineer",
    "Virtualization Engineer",
    "Artificial Intelligence Research Scientist",
    "Robotics Engineer",
    "Mobile Security Specialist",
    "Network Security Engineer",
    "Solutions Architect",
    "DevSecOps Engineer",
    "Cloud Security Engineer",
    "IT Vendor Manager",
    "CRM Developer",
    "Technical Lead",
    "IT Asset Manager",
    "Application Developer",
    "Mobile Game Developer",
    "Computer Vision Engineer",
    "Natural Language Processing Engineer",
    "Technical Support Specialist",
    "Storage Engineer",
    "IT Business Relationship Manager",
    "Blockchain Architect",
    "IT Operations Analyst",
    "Cybersecurity Engineer",
    "Augmented Reality Developer",
    "Virtual Reality Developer",
    "GIS Developer",
    "Technical Product Owner",
    "Scrum Master",
    "IT Compliance Analyst",
    "Digital Transformation Consultant",
    "Automation Engineer"
];

export const locations = [
    "Mumbai, Maharashtra",
    "Delhi, Delhi",
    "Bengaluru, Karnataka",
    "Hyderabad, Telangana",
    "Ahmedabad, Gujarat",
    "Chennai, Tamil Nadu",
    "Kolkata, West Bengal",
    "Surat, Gujarat",
    "Pune, Maharashtra",
    "Jaipur, Rajasthan",
    "Lucknow, Uttar Pradesh",
    "Kanpur, Uttar Pradesh",
    "Nagpur, Maharashtra",
    "Indore, Madhya Pradesh",
    "Thane, Maharashtra",
    "Bhopal, Madhya Pradesh",
    "Visakhapatnam, Andhra Pradesh",
    "Pimpri-Chinchwad, Maharashtra",
    "Patna, Bihar",
    "Vadodara, Gujarat",
    "Ghaziabad, Uttar Pradesh",
    "Ludhiana, Punjab",
    "Agra, Uttar Pradesh",
    "Nashik, Maharashtra",
    "Faridabad, Haryana",
    "Meerut, Uttar Pradesh",
    "Rajkot, Gujarat",
    "Kalyan-Dombivli, Maharashtra",
    "Vasai-Virar, Maharashtra",
    "Varanasi, Uttar Pradesh",
    "Srinagar, Jammu and Kashmir",
    "Aurangabad, Maharashtra",
    "Dhanbad, Jharkhand",
    "Amritsar, Punjab",
    "Navi Mumbai, Maharashtra",
    "Allahabad, Uttar Pradesh",
    "Ranchi, Jharkhand",
    "Howrah, West Bengal",
    "Coimbatore, Tamil Nadu",
    "Jabalpur, Madhya Pradesh",
    "Gwalior, Madhya Pradesh",
    "Vijayawada, Andhra Pradesh",
    "Jodhpur, Rajasthan",
    "Madurai, Tamil Nadu",
    "Raipur, Chhattisgarh",
    "Kota, Rajasthan",
    "Guwahati, Assam",
    "Chandigarh, Chandigarh",
    "Solapur, Maharashtra",
    "Hubballi-Dharwad, Karnataka",
    "Bareilly, Uttar Pradesh",
    "Mysore, Karnataka",
    "Tiruchirappalli, Tamil Nadu",
    "Gurgaon, Haryana",
    "Aligarh, Uttar Pradesh",
    "Jalandhar, Punjab",
    "Bhubaneswar, Odisha",
    "Salem, Tamil Nadu",
    "Mira-Bhayandar, Maharashtra",
    "Warangal, Telangana",
    "Guntur, Andhra Pradesh",
    "Bhiwandi, Maharashtra",
    "Saharanpur, Uttar Pradesh",
    "Gorakhpur, Uttar Pradesh",
    "Bikaner, Rajasthan",
    "Amravati, Maharashtra",
    "Noida, Uttar Pradesh",
    "Jamshedpur, Jharkhand",
    "Bhilai, Chhattisgarh",
    "Cuttack, Odisha",
    "Firozabad, Uttar Pradesh",
    "Kochi, Kerala",
    "Bhavnagar, Gujarat",
    "Dehradun, Uttarakhand",
    "Durgapur, West Bengal",
    "Asansol, West Bengal",
    "Nanded, Maharashtra",
    "Kolhapur, Maharashtra",
    "Ajmer, Rajasthan",
    "Gulbarga, Karnataka",
    "Jammu, Jammu and Kashmir",
    "Ujjain, Madhya Pradesh",
    "Loni, Uttar Pradesh",
    "Siliguri, West Bengal",
    "Jhansi, Uttar Pradesh",
    "Ulhasnagar, Maharashtra",
    "Jammu, Jammu and Kashmir",
    "Sangli-Miraj & Kupwad, Maharashtra",
    "Sambalpur, Odisha",
    "Karnal, Haryana",
    "Shimla, Himachal Pradesh",
    "Rohtak, Haryana",
    "Panipat, Haryana",
    "Bilaspur, Chhattisgarh",
    "Tirupati, Andhra Pradesh",
    "Mathura, Uttar Pradesh",
    "Patiala, Punjab",
    "Alappuzha, Kerala",
    "Gandhinagar, Gujarat",
    "Kollam, Kerala",
    "Nandurbar, Maharashtra",
    "Anantapur, Andhra Pradesh",
    "Thanjavur, Tamil Nadu",
    "Bardhaman, West Bengal",
    "Ozhukarai, Puducherry",
    "Bathinda, Punjab",
    "Gopalpur, Odisha",
    "Guntakal, Andhra Pradesh",
    "Hoshiarpur, Punjab",
    "Kurukshetra, Haryana",
    "Raebareli, Uttar Pradesh",
    "Muzaffarnagar, Uttar Pradesh",
    "Palakkad, Kerala",
    "Haridwar, Uttarakhand",
    "Bhadravati, Karnataka",
    "Chittoor, Andhra Pradesh",
    "Raurkela, Odisha",
    "Mancherial, Telangana",
    "Chandrapur, Maharashtra",
    "Budaun, Uttar Pradesh",
    "Hapur, Uttar Pradesh",
    "Rae Bareli, Uttar Pradesh",
    "Port Blair, Andaman and Nicobar Islands",
    "Purulia, West Bengal"
];

export const states = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttarakhand",
    "Uttar Pradesh",
    "West Bengal",
]

export const levelOfEducation = [
    "No formal education",
    "Primary (1-5)",
    "Middle (6-8)",
    "High School (9-10)",
    "Higher Secondary (11-12)",
    "Diploma",
    "Graduate",
    "Post Graduate",
    "Doctoral",
]

export const fieldOfStudy = [
    "Arts",
    "Commerce",
    "Science",
    "Engineering",
    "Medicine",
    "Computer Science",
]

export const cities = {
    "Andhra Pradesh": [
        "Visakhapatnam",
        "Vijayawada",
        "Guntur",
        "Nellore",
        "Kurnool",
        "Rajahmundry",
        "Kakinada",
        "Tirupati",
        "Kadapa",
        "Anantapur",
        "Eluru",
        "Vizianagaram",
        "Ongole",
        "Tenali",
        "Chittoor",
        "Machilipatnam",
        "Proddatur",
        "Adoni",
        "Madanapalle",
        "Nandyal",
        "Tadepalligudem",
        "Chirala",
        "Hindupur",
        "Bhimavaram"
    ],
    "Arunachal Pradesh": [
        "Itanagar",
        "Tawang",
        "Pasighat",
        "Ziro",
        "Bomdila",
        "Aalo",
        "Daporijo",
        "Tezu",
        "Roing",
        "Changlang",
        "Khonsa",
        "Namsai",
        "Yingkiong",
        "Seppa",
        "Anini",
        "Koloriang",
        "Basar",
        "Longding"
    ],
    "Assam": [
        "Guwahati",
        "Dibrugarh",
        "Silchar",
        "Jorhat",
        "Nagaon",
        "Tinsukia",
        "Tezpur",
        "Bongaigaon",
        "Sivasagar",
        "Karimganj",
        "Golaghat",
        "Lakhimpur",
        "Dhubri",
        "Barpeta",
        "Goalpara",
        "Hailakandi",
        "Bongaigaon",
        "Kokrajhar",
        "Morigaon",
        "Rangia",
        "Diphu",
        "Haflong",
        "Mangaldoi"
    ],
    "Bihar": [
        "Patna",
        "Gaya",
        "Bhagalpur",
        "Muzaffarpur",
        "Purnia",
        "Darbhanga",
        "Bihar Sharif",
        "Arrah",
        "Begusarai",
        "Katihar",
        "Munger",
        "Chhapra",
        "Sasaram",
        "Hajipur",
        "Dehri",
        "Bettiah",
        "Motihari",
        "Samastipur",
        "Siwan",
        "Aurangabad",
        "Saharsa",
        "Nawada",
        "Buxar",
        "Kishanganj",
        "Sitamarhi"
    ],
    "Chhattisgarh": [
        "Raipur",
        "Bhilai",
        "Bilaspur",
        "Korba",
        "Durg",
        "Rajnandgaon",
        "Jagdalpur",
        "Raigarh",
        "Ambikapur",
        "Dhamtari",
        "Mahasamund",
        "Kanker",
        "Kondagaon",
        "Bijapur",
        "Dantewada",
        "Sukma",
        "Narayanpur",
        "Mungeli",
        "Surajpur",
        "Balrampur"
    ],
    "Goa": [
        "Panaji",
        "Margao",
        "Vasco da Gama",
        "Mapusa",
        "Ponda",
        "Bicholim",
        "Curchorem",
        "Valpoi",
        "Canacona",
        "Quepem",
        "Sanguem",
        "Mormugao",
        "Pernem",
        "Sanquelim",
        "Saligao"
    ],
    "Gujarat": [
        "Ahmedabad",
        "Surat",
        "Vadodara",
        "Rajkot",
        "Bhavnagar",
        "Jamnagar",
        "Gandhinagar",
        "Junagadh",
        "Anand",
        "Navsari",
        "Bharuch",
        "Porbandar",
        "Morbi",
        "Nadiad",
        "Mehsana",
        "Bhuj",
        "Surendranagar",
        "Gandhidham",
        "Vapi",
        "Veraval",
        "Palanpur",
        "Botad",
        "Dahod",
        "Valsad",
        "Godhra"
    ],
    "Haryana": [
        "Chandigarh",
        "Gurugram",
        "Faridabad",
        "Panipat",
        "Karnal",
        "Ambala",
        "Yamunanagar",
        "Rohtak",
        "Hisar",
        "Sonipat",
        "Panchkula",
        "Bhiwani",
        "Sirsa",
        "Jind",
        "Thanesar",
        "Bahadurgarh",
        "Kaithal",
        "Rewari",
        "Palwal",
        "Hansi",
        "Narwana",
        "Fatehabad",
        "Gohana",
        "Jhajjar",
        "Narnaul"
    ],
    "Himachal Pradesh": [
        "Shimla",
        "Manali",
        "Dharamshala",
        "Kullu",
        "Solan",
        "Mandi",
        "Bilaspur",
        "Chamba",
        "Kangra",
        "Una",
        "Hamirpur",
        "Kinnaur",
        "Keylong",
        "Palampur",
        "Sundarnagar",
        "Nahan",
        "Dalhousie",
        "Parwanoo"
    ],
    "Jammu and Kashmir": [
        "Srinagar",
        "Jammu",
        "Anantnag",
        "Baramulla",
        "Kathua",
        "Udhampur",
        "Sopore",
        "Rajouri",
        "Poonch",
        "Kupwara",
        "Pulwama",
        "Badgam",
        "Ganderbal",
        "Bandipora",
        "Handwara",
        "Kulgam",
        "Shopian"
    ],
    "Jharkhand": [
        "Ranchi",
        "Jamshedpur",
        "Dhanbad",
        "Bokaro",
        "Deoghar",
        "Hazaribagh",
        "Giridih",
        "Ramgarh",
        "Chakradharpur",
        "Chaibasa",
        "Dumka",
        "Phusro",
        "Gumia",
        "Gumla",
        "Medininagar",
        "Lohardaga",
        "Sahibganj",
        "Pakur",
        "Simdega"
    ],
    "Karnataka": [
        "Bengaluru",
        "Mysuru",
        "Hubli-Dharwad",
        "Mangaluru",
        "Belagavi",
        "Gulbarga",
        "Bellary",
        "Bijapur",
        "Tumkur",
        "Shimoga",
        "Davangere",
        "Udupi",
        "Chitradurga",
        "Chikkamagaluru",
        "Hassan",
        "Bidar",
        "Raichur",
        "Bagalkot",
        "Mandya",
        "Kolar"
    ],
    "Kerala": [
        "Thiruvananthapuram",
        "Kochi",
        "Kozhikode",
        "Kollam",
        "Thrissur",
        "Alappuzha",
        "Palakkad",
        "Kannur",
        "Kottayam",
        "Malappuram",
        "Kasaragod",
        "Pathanamthitta",
        "Idukki",
        "Wayanad"
    ],
    "Madhya Pradesh": [
        "Bhopal",
        "Indore",
        "Gwalior",
        "Jabalpur",
        "Ujjain",
        "Sagar",
        "Ratlam",
        "Rewa",
        "Satna",
        "Dewas",
        "Murwara",
        "Singrauli",
        "Burhanpur",
        "Chhindwara",
        "Morena",
        "Khargone",
        "Vidisha",
        "Neemuch",
        "Hoshangabad"
    ],
    "Maharashtra": [
        "Mumbai",
        "Pune",
        "Nagpur",
        "Thane",
        "Nashik",
        "Aurangabad",
        "Solapur",
        "Amravati",
        "Kolhapur",
        "Akola",
        "Latur",
        "Dhule",
        "Jalgaon",
        "Nanded",
        "Sangli",
        "Ratnagiri",
        "Chandrapur",
        "Parbhani",
        "Beed"
    ],
    "Manipur": [
        "Imphal",
        "Thoubal",
        "Bishnupur",
        "Churachandpur",
        "Senapati",
        "Ukhrul",
        "Kakching",
        "Tamenglong",
        "Moreh",
        "Jiribam",
        "Noney",
        "Pherzawl"
    ],
    "Meghalaya": [
        "Shillong",
        "Tura",
        "Nongstoin",
        "Jowai",
        "Baghmara",
        "Williamnagar",
        "Mairang",
        "Resubelpara",
        "Khliehriat",
        "Ampati"
    ],
    "Mizoram": [
        "Aizawl",
        "Lunglei",
        "Saiha",
        "Champhai",
        "Kolasib",
        "Serchhip",
        "Lawngtlai",
        "Mamit"
    ],
    "Nagaland": [
        "Kohima",
        "Dimapur",
        "Mokokchung",
        "Tuensang",
        "Wokha",
        "Zunheboto",
        "Phek",
        "Kiphire",
        "Mon",
        "Longleng",
        "Peren"
    ],
    "Odisha": [
        "Bhubaneswar",
        "Cuttack",
        "Rourkela",
        "Brahmapur",
        "Sambalpur",
        "Puri",
        "Balasore",
        "Baripada",
        "Bhadrak",
        "Jeypore",
        "Jharsuguda",
        "Balangir",
        "Angul",
        "Dhenkanal",
        "Paradeep",
        "Kendujhar",
        "Nabarangpur",
        "Bargarh"
    ],
    "Punjab": [
        "Ludhiana",
        "Amritsar",
        "Jalandhar",
        "Patiala",
        "Bathinda",
        "Mohali",
        "Hoshiarpur",
        "Batala",
        "Pathankot",
        "Moga",
        "Abohar",
        "Malerkotla",
        "Khanna",
        "Phagwara",
        "Muktsar",
        "Barnala",
        "Rajpura"
    ],
    "Rajasthan": [
        "Jaipur",
        "Jodhpur",
        "Kota",
        "Bikaner",
        "Ajmer",
        "Udaipur",
        "Bhilwara",
        "Alwar",
        "Bharatpur",
        "Sikar",
        "Pali",
        "Tonk",
        "Beawar",
        "Sawai Madhopur",
        "Nagaur",
        "Chittorgarh",
        "Hanumangarh"
    ],
    "Sikkim": [
        "Gangtok",
        "Namchi",
        "Mangan",
        "Geyzing",
        "Rangpo",
        "Singtam",
        "Jorethang"
    ],
    "Tamil Nadu": [
        "Chennai",
        "Coimbatore",
        "Madurai",
        "Tiruchirappalli",
        "Salem",
        "Erode",
        "Tirunelveli",
        "Vellore",
        "Tiruppur",
        "Thoothukudi",
        "Nagercoil",
        "Cuddalore",
        "Kanchipuram",
        "Thanjavur",
        "Dindigul",
        "Kumbakonam",
        "Karaikudi"
    ],
    "Telangana": [
        "Hyderabad",
        "Warangal",
        "Nizamabad",
        "Khammam",
        "Karimnagar",
        "Ramagundam",
        "Mahbubnagar",
        "Nalgonda",
        "Adilabad",
        "Suryapet",
        "Miryalaguda",
        "Siddipet",
        "Kamareddy",
        "Jagtial",
        "Mancherial"
    ],
    "Tripura": [
        "Agartala",
        "Udaipur",
        "Dharmanagar",
        "Kailasahar",
        "Belonia",
        "Khowai",
        "Ambassa"
    ],
    "Uttarakhand": [
        "Almora",
        "Bageshwar",
        "Dehradun",
        "Haridwar",
        "Roorkee",
        "Haldwani",
        "Rishikesh",
        "Kashipur",
        "Rudrapur",
        "Nainital",
        "Pithoragarh",
        "Mussoorie",
        "Tehri",
        "Srinagar"
    ],
    "Uttar Pradesh": [
        "Lucknow",
        "Kanpur",
        "Ghaziabad",
        "Agra",
        "Meerut",
        "Varanasi",
        "Allahabad",
        "Bareilly",
        "Aligarh",
        "Moradabad",
        "Saharanpur",
        "Gorakhpur",
        "Noida",
        "Firozabad",
        "Jhansi",
        "Muzaffarnagar",
        "Mathura",
        "Rampur",
        "Shahjahanpur",
        "Faizabad",
        "Budaun",
        "Bijnor",
        "Bulandshahar",
        "Etawah",
        "Hapur",
        "Azamgarh",
        "Ballia",
        "Banda",
        "Unnao",
    ],
    "West Bengal": [
        "Kolkata",
        "Howrah",
        "Durgapur",
        "Asansol",
        "Siliguri",
        "Bardhaman",
        "Berhampore",
        "Kharagpur",
        "Malda",
        "Alipurduar",
        "Haldia",
        "Ranaghat",
        "Jalpaiguri",
        "Chandannagar",
        "Nabadwip",
        "Medinipur",
        "Bangaon",
        "Raiganj",
        "Balurghat",
        "Cooch Behar",
        "Purulia",
        "Krishnanagar",
        "Bankura",
        "Bolpur",
        "Suri"
    ],
}

export const industries = [
    "Software Development", "Application Development", "Web Development", "Mobile App Development",
    "IT Services", "Consulting", "Support", "Maintenance",
    "Cloud Computing", "Infrastructure as a Service (IaaS)", "Platform as a Service (PaaS)", "Software as a Service (SaaS)",
    "Cybersecurity", "Network Security", "Information Security", "Incident Response",
    "Data Analytics", "Business Intelligence", "Big Data Analytics", "Data Warehousing",
    "Artificial Intelligence", "Machine Learning", "Natural Language Processing", "Computer Vision",
    "Internet of Things", "Smart Devices", "Wearable Technology", "Connected Vehicles",
    "E-commerce", "Online Retail", "Payment Processing", "Digital Marketing",
    "Blockchain", "Cryptocurrency", "Smart Contracts", "Supply Chain Management",
    "Robotics", "Industrial Automation", "Service Robots", "Medical Robotics"
]

export const employmentTypes = [
    "Full-time",
    "Part-time",
    "Internship",
    "Contract",
    "Freelance",
]

export const jobTypes = [
    "Designing",
    "Technical",
    "Marketing",
    "Sales",
    "Customer Support",
    "Finance",
    "Human Resources",
    "Operations",
]

export const skills = [
    "Python",
    "Java",
    "JavaScript",
    "C++",
    "C#",
    "Ruby",
    "Swift",
    "PHP",
    "Go",
    "Kotlin",
    "Rust",
    "TypeScript",
    "SQL",
    "NoSQL",
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Vue",
    "Django",
    "Flask",
    "Spring",
    "Node.js",
    "AWS",
    "Azure",
    "Google Cloud",
    "Next js",
    "React Native",
    "Redux"
]

export const colors = ['Black', 'Gray', 'Red', 'Pink', 'Orange', 'Yellow', 'Green', 'Teal', 'Cyan', 'Blue', 'Violet', 'Indigo']


export const myCommunites = [
    {
        "name": "Nature Enthusiasts",
        "description": "A community for people who love exploring nature",
        "owner": "605c72a95f1b2c001a5a1d1f",
        "members": ["605c72a95f1b2c001a5a1d20", "605c72a95f1b2c001a5a1d21"],
        "banned": ["605c72a95f1b2c001a5a1d22"],
        "avatar": "https://th.bing.com/th/id/OIP.Kg6YNNbgzoyNhJ_oTdr54gHaCT?rs=1&pid=ImgDetMain",
        "coverImage": "https://th.bing.com/th/id/OIP.Kg6YNNbgzoyNhJ_oTdr54gHaCT?rs=1&pid=ImgDetMain"
    },
    {
        "name": "Tech Geeks",
        "description": "A community for tech lovers and innovators",
        "owner": "605c72a95f1b2c001a5a1d23",
        "members": ["605c72a95f1b2c001a5a1d24", "605c72a95f1b2c001a5a1d25"],
        "banned": ["605c72a95f1b2c001a5a1d26"],
        "avatar": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/ec1b11153202773.632b53f3c037f.png",
        "coverImage": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/ec1b11153202773.632b53f3c037f.png"
    },
    {
        "name": "Book Club",
        "description": "A community for book lovers and literature enthusiasts",
        "owner": "605c72a95f1b2c001a5a1d27",
        "members": ["605c72a95f1b2c001a5a1d28", "605c72a95f1b2c001a5a1d29"],
        "banned": ["605c72a95f1b2c001a5a1d2a"],
        "avatar": "https://th.bing.com/th/id/OIP.IMokSlMxGcePyNhFe6YtigHaEK?rs=1&pid=ImgDetMain",
        "coverImage": "https://th.bing.com/th/id/OIP.IMokSlMxGcePyNhFe6YtigHaEK?rs=1&pid=ImgDetMain"
    },
    {
        "name": "Fitness Freaks",
        "description": "A community for fitness enthusiasts and health-conscious people",
        "owner": "605c72a95f1b2c001a5a1d2b",
        "members": ["605c72a95f1b2c001a5a1d2c", "605c72a95f1b2c001a5a1d2d"],
        "banned": ["605c72a95f1b2c001a5a1d2e"],
        "avatar": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/ec1b11153202773.632b53f3c037f.png",
        "coverImage": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/ec1b11153202773.632b53f3c037f.png"
    },
    {
        "name": "Art Lovers",
        "description": "A community for art enthusiasts and creators",
        "owner": "605c72a95f1b2c001a5a1d2f",
        "members": ["605c72a95f1b2c001a5a1d30", "605c72a95f1b2c001a5a1d31"],
        "banned": ["605c72a95f1b2c001a5a1d32"],
        "avatar": "https://th.bing.com/th/id/OIP.IMokSlMxGcePyNhFe6YtigHaEK?rs=1&pid=ImgDetMain",
        "coverImage": "https://th.bing.com/th/id/OIP.IMokSlMxGcePyNhFe6YtigHaEK?rs=1&pid=ImgDetMain"
    },
]
